name: Smart Contract CI/CD

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and test backend
        run: |
          docker compose build backend
          docker compose run --rm backend npm run test
          docker compose run --rm backend npx hardhat compile
          docker compose run --rm backend npx solhint 'contracts/**/*.sol'

      - name: Install and run Slither
        run: |
          python3 -m pip install --user slither-analyzer
          docker compose run --rm backend slither . --config-file slither.config.json

  deploy:
    needs: build-test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Deploy to Sepolia
        run: |
          docker compose run --rm \
            -e PRIVATE_KEY=${{ secrets.PRIVATE_KEY }} \
            -e ALCHEMY_SEPOLIA_URL=${{ secrets.ALCHEMY_SEPOLIA_URL }} \
            backend npx hardhat run scripts/deploy.js --network sepolia
          echo "CONTRACT_ADDRESS=$(docker compose run --rm backend cat deployment.txt)" >> $GITHUB_OUTPUT

      - name: Notify deployment
        if: success()
        run: |
          echo "Contract deployed successfully to ${{ steps.deploy.outputs.CONTRACT_ADDRESS }}"
